version: "3.9"
services:
  db_sso:
    container_name: sso-db
    image: postgres:16
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_sso_data:/var/lib/postgresql/data
  sso:
    container_name: sso
    image: antgoncharik/sso
    env_file:
      - .env
    restart: always
    volumes:
      - ./config/rsa:/opt/app/config/rsa
    depends_on:
      db_sso:
        condition: service_healthy
volumes:
  db_sso_data:
